/**
 * PDF rendering port.
 *
 * Official PDFs are generated by the backend from saved database records, never
 * from data supplied by the browser.
 *
 * See docs/technical-blueprint.md section 9.
 */

export interface RenderPdfInput {
  /** Fully rendered HTML document. */
  html: string;
  /** Shown in PDF metadata. */
  documentTitle: string;
}

export interface RenderedPdf {
  content: Buffer;
  /** SHA-256 of the rendered bytes, stored with issued documents. */
  checksum: string;
}

export interface PdfRenderer {
  readonly name: string;
  render(input: RenderPdfInput): Promise<RenderedPdf>;
}
