import type { ExportColumn } from './export.types.js';

const KES: ExportColumn['format'] = 'KES';
const INT: ExportColumn['format'] = 'int';
const DATE: ExportColumn['format'] = 'date';
const L = 'left' as const; const R = 'right' as const; const C = 'center' as const;

// ── Report columns ─────────────────────────────────────────────────

export const REPORT_COLUMNS: Record<string, ExportColumn[]> = {
  'reports/orders': [
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'itemCount', header: 'Items', width: 8, align: R, format: INT },
    { key: 'total', header: 'Total (KES)', width: 16, align: R, format: KES },
    { key: 'amountPaid', header: 'Paid (KES)', width: 16, align: R, format: KES },
    { key: 'outstanding', header: 'Outstanding (KES)', width: 18, align: R, format: KES },
    { key: 'paymentStatus', header: 'Payment Status', width: 16, align: L },
    { key: 'fulfillmentStatus', header: 'Fulfillment Status', width: 18, align: L },
  ],
  'reports/top-orders': [
    { key: 'rank', header: '#', width: 6, align: R, format: INT },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'total', header: 'Total (KES)', width: 16, align: R, format: KES },
    { key: 'amountPaid', header: 'Paid (KES)', width: 16, align: R, format: KES },
    { key: 'outstanding', header: 'Outstanding (KES)', width: 18, align: R, format: KES },
    { key: 'paymentStatus', header: 'Payment Status', width: 16, align: L },
    { key: 'fulfillmentStatus', header: 'Fulfillment Status', width: 18, align: L },
  ],
  'reports/top-customers': [
    { key: 'rank', header: '#', width: 6, align: R, format: INT },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'orderCount', header: 'Orders', width: 10, align: R, format: INT },
    { key: 'paymentCount', header: 'Payments', width: 10, align: R, format: INT },
    { key: 'totalInvoiced', header: 'Invoiced (KES)', width: 16, align: R, format: KES },
    { key: 'paymentsReceived', header: 'Received (KES)', width: 16, align: R, format: KES },
    { key: 'outstanding', header: 'Outstanding (KES)', width: 18, align: R, format: KES },
  ],
  'reports/customer-balances': [
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'phone', header: 'Phone', width: 16, align: L },
    { key: 'openingBalance', header: 'Opening Bal. (KES)', width: 18, align: R, format: KES },
    { key: 'totalInvoiced', header: 'Invoiced (KES)', width: 16, align: R, format: KES },
    { key: 'approvedPayments', header: 'Approved Payments (KES)', width: 20, align: R, format: KES },
    { key: 'outstanding', header: 'Outstanding (KES)', width: 18, align: R, format: KES },
    { key: 'creditStatus', header: 'Credit Status', width: 14, align: L },
  ],
  'reports/invoices': [
    { key: 'invoiceNumber', header: 'Invoice #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'total', header: 'Total (KES)', width: 16, align: R, format: KES },
    { key: 'amountPaid', header: 'Paid (KES)', width: 16, align: R, format: KES },
    { key: 'outstanding', header: 'Outstanding (KES)', width: 18, align: R, format: KES },
    { key: 'invoiceStatus', header: 'Invoice Status', width: 14, align: L },
    { key: 'paymentStatus', header: 'Payment Status', width: 16, align: L },
  ],
  'reports/payments': [
    { key: 'paymentNumber', header: 'Payment #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'method', header: 'Method', width: 14, align: L },
    { key: 'reference', header: 'Reference', width: 20, align: L },
    { key: 'status', header: 'Status', width: 12, align: L },
    { key: 'invoiceNumbers', header: 'Invoices', width: 24, align: L },
    { key: 'receiptNumber', header: 'Receipt #', width: 16, align: L },
  ],
  'reports/receipts': [
    { key: 'receiptNumber', header: 'Receipt #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'paymentNumber', header: 'Payment #', width: 16, align: L },
    { key: 'invoiceNumber', header: 'Invoice #', width: 16, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
    { key: 'status', header: 'Status', width: 10, align: L },
  ],
  'reports/production': [
    { key: 'productionNumber', header: 'Batch #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'purpose', header: 'Purpose', width: 14, align: L },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'productCount', header: 'Products', width: 10, align: R, format: INT },
    { key: 'totalProduced', header: 'Produced', width: 12, align: R, format: INT },
    { key: 'totalBroken', header: 'Broken', width: 10, align: R, format: INT },
    { key: 'totalUsable', header: 'Usable', width: 10, align: R, format: INT },
    { key: 'status', header: 'Status', width: 14, align: L },
  ],
  'reports/curing': [
    { key: 'productionNumber', header: 'Batch #', width: 16, align: L },
    { key: 'productName', header: 'Product', width: 20, align: L },
    { key: 'quantityEntering', header: 'Entering', width: 12, align: R, format: INT },
    { key: 'duration', header: 'Duration', width: 10, align: L },
    { key: 'startedAt', header: 'Started', width: 12, align: L, format: DATE },
    { key: 'plannedCompletion', header: 'Planned', width: 12, align: L, format: DATE },
    { key: 'actualRelease', header: 'Released', width: 12, align: L, format: DATE },
    { key: 'brokenQuantity', header: 'Broken', width: 10, align: R, format: INT },
    { key: 'releasedQuantity', header: 'Rel. Qty', width: 10, align: R, format: INT },
  ],
  'reports/deliveries': [
    { key: 'deliveryNumber', header: 'Delivery #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'driverName', header: 'Driver', width: 20, align: L },
    { key: 'vehicleReg', header: 'Vehicle', width: 14, align: L },
    { key: 'itemCount', header: 'Items', width: 8, align: R, format: INT },
    { key: 'totalQuantity', header: 'Qty', width: 10, align: R, format: INT },
    { key: 'transportCost', header: 'Transport (KES)', width: 16, align: R, format: KES },
    { key: 'status', header: 'Status', width: 12, align: L },
  ],
  'reports/finished-stock': [
    { key: 'productName', header: 'Product', width: 24, align: L },
    { key: 'physicalQuantity', header: 'Physical', width: 12, align: R, format: INT },
    { key: 'reservedQuantity', header: 'Reserved', width: 12, align: R, format: INT },
    { key: 'availableQuantity', header: 'Available', width: 12, align: R, format: INT },
  ],
  'reports/reserved-stock': [
    { key: 'productName', header: 'Product', width: 24, align: L },
    { key: 'physicalQuantity', header: 'Physical', width: 12, align: R, format: INT },
    { key: 'reservedQuantity', header: 'Reserved', width: 12, align: R, format: INT },
    { key: 'availableQuantity', header: 'Available', width: 12, align: R, format: INT },
  ],
  'reports/available-stock': [
    { key: 'productName', header: 'Product', width: 24, align: L },
    { key: 'physicalQuantity', header: 'Physical', width: 12, align: R, format: INT },
    { key: 'reservedQuantity', header: 'Reserved', width: 12, align: R, format: INT },
    { key: 'availableQuantity', header: 'Available', width: 12, align: R, format: INT },
  ],
  'reports/low-stock': [
    { key: 'productName', header: 'Product', width: 24, align: L },
    { key: 'physicalQuantity', header: 'Physical', width: 12, align: R, format: INT },
    { key: 'reservedQuantity', header: 'Reserved', width: 12, align: R, format: INT },
    { key: 'availableQuantity', header: 'Available', width: 12, align: R, format: INT },
    { key: 'reorderLevel', header: 'Reorder Level', width: 14, align: R, format: INT },
  ],
  'reports/stock-movement': [
    { key: 'date', header: 'Date/Time', width: 18, align: L },
    { key: 'productName', header: 'Product', width: 20, align: L },
    { key: 'movementType', header: 'Type', width: 20, align: L },
    { key: 'quantityIn', header: 'In', width: 10, align: R, format: INT },
    { key: 'quantityOut', header: 'Out', width: 10, align: R, format: INT },
    { key: 'balanceAfter', header: 'Balance', width: 12, align: R, format: INT },
    { key: 'reason', header: 'Reason', width: 24, align: L },
  ],
  'reports/purchases': [
    { key: 'purchaseNumber', header: 'Purchase #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'supplierName', header: 'Supplier', width: 24, align: L },
    { key: 'reference', header: 'Reference', width: 20, align: L },
    { key: 'itemCount', header: 'Items', width: 8, align: R, format: INT },
    { key: 'totalCost', header: 'Total Cost (KES)', width: 18, align: R, format: KES },
  ],
  'reports/purchase-payments': [
    { key: 'paymentNumber', header: 'Payment #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'supplierName', header: 'Supplier', width: 24, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'method', header: 'Method', width: 14, align: L },
    { key: 'reference', header: 'Reference', width: 20, align: L },
    { key: 'status', header: 'Status', width: 12, align: L },
    { key: 'purchaseNumbers', header: 'Purchases', width: 24, align: L },
  ],
  'reports/suppliers': [
    { key: 'supplierName', header: 'Supplier', width: 24, align: L },
    { key: 'phone', header: 'Phone', width: 16, align: L },
    { key: 'openingBalance', header: 'Opening Bal. (KES)', width: 18, align: R, format: KES },
    { key: 'totalPurchases', header: 'Purchases (KES)', width: 16, align: R, format: KES },
    { key: 'approvedPayments', header: 'Approved Pmts (KES)', width: 18, align: R, format: KES },
    { key: 'outstanding', header: 'Outstanding (KES)', width: 18, align: R, format: KES },
  ],
  'reports/expenses': [
    { key: 'expenseNumber', header: 'Expense #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'category', header: 'Category', width: 16, align: L },
    { key: 'description', header: 'Description', width: 32, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
    { key: 'paymentReference', header: 'Reference', width: 20, align: L },
  ],
  'reports/salaries': [
    { key: 'salaryNumber', header: 'Salary #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'employeeName', header: 'Employee', width: 24, align: L },
    { key: 'salaryType', header: 'Type', width: 10, align: L },
    { key: 'periodStart', header: 'Period Start', width: 12, align: L, format: DATE },
    { key: 'periodEnd', header: 'Period End', width: 12, align: L, format: DATE },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
    { key: 'status', header: 'Status', width: 12, align: L },
  ],
  'reports/outstanding-invoices': [
    { key: 'invoiceNumber', header: 'Invoice #', width: 16, align: L },
    { key: 'date', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'total', header: 'Total (KES)', width: 16, align: R, format: KES },
    { key: 'amountPaid', header: 'Paid (KES)', width: 16, align: R, format: KES },
    { key: 'outstanding', header: 'Outstanding (KES)', width: 18, align: R, format: KES },
    { key: 'paymentStatus', header: 'Payment', width: 14, align: L },
  ],
  'reports/billing-summary': [
    { key: 'label', header: 'Period', width: 12, align: L },
    { key: 'invoiced', header: 'Invoiced (KES)', width: 16, align: R, format: KES },
    { key: 'received', header: 'Received (KES)', width: 16, align: R, format: KES },
    { key: 'expenses', header: 'Expenses (KES)', width: 16, align: R, format: KES },
    { key: 'salaries', header: 'Salaries (KES)', width: 16, align: R, format: KES },
  ],
};

// ── List page columns ─────────────────────────────────────────────

export const LIST_COLUMNS: Record<string, ExportColumn[]> = {
  orders: [
    { key: 'orderNumber', header: 'Order #', width: 14, align: L },
    { key: 'createdAt', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'paymentArrangement', header: 'Payment', width: 12, align: L },
    { key: 'itemCount', header: 'Items', width: 8, align: R, format: INT },
    { key: 'totalAmount', header: 'Total (KES)', width: 16, align: R, format: KES },
    { key: 'status', header: 'Status', width: 16, align: L },
  ],
  customers: [
    { key: 'name', header: 'Name', width: 24, align: L },
    { key: 'phone', header: 'Phone', width: 16, align: L },
    { key: 'email', header: 'Email', width: 28, align: L },
    { key: 'isActive', header: 'Active', width: 8, align: C },
  ],
  invoices: [
    { key: 'invoiceNumber', header: 'Invoice #', width: 16, align: L },
    { key: 'createdAt', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'totalAmount', header: 'Total (KES)', width: 16, align: R, format: KES },
    { key: 'paymentStatus', header: 'Payment Status', width: 16, align: L },
    { key: 'status', header: 'Status', width: 10, align: L },
  ],
  payments: [
    { key: 'paymentNumber', header: 'Payment #', width: 16, align: L },
    { key: 'paymentDate', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
    { key: 'status', header: 'Status', width: 12, align: L },
  ],
  receipts: [
    { key: 'receiptNumber', header: 'Receipt #', width: 16, align: L },
    { key: 'issuedAt', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'status', header: 'Status', width: 10, align: L },
  ],
  expenses: [
    { key: 'expenseNumber', header: 'Expense #', width: 16, align: L },
    { key: 'expenseDate', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'category', header: 'Category', width: 16, align: L },
    { key: 'description', header: 'Description', width: 32, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
  ],
  employees: [
    { key: 'name', header: 'Name', width: 24, align: L },
    { key: 'phone', header: 'Phone', width: 16, align: L },
    { key: 'jobTitle', header: 'Job Title', width: 20, align: L },
    { key: 'salaryType', header: 'Salary Type', width: 12, align: L },
    { key: 'salaryAmount', header: 'Salary (KES)', width: 14, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
    { key: 'isActive', header: 'Active', width: 8, align: C },
  ],
  salaries: [
    { key: 'salaryNumber', header: 'Salary #', width: 16, align: L },
    { key: 'paymentDate', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'employeeName', header: 'Employee', width: 24, align: L },
    { key: 'salaryType', header: 'Type', width: 10, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
    { key: 'status', header: 'Status', width: 12, align: L },
  ],
  suppliers: [
    { key: 'name', header: 'Name', width: 24, align: L },
    { key: 'phone', header: 'Phone', width: 16, align: L },
    { key: 'email', header: 'Email', width: 28, align: L },
    { key: 'address', header: 'Address', width: 32, align: L },
    { key: 'isActive', header: 'Active', width: 8, align: C },
  ],
  purchases: [
    { key: 'purchaseNumber', header: 'Purchase #', width: 16, align: L },
    { key: 'purchaseDate', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'supplierName', header: 'Supplier', width: 24, align: L },
    { key: 'totalCost', header: 'Total Cost (KES)', width: 18, align: R, format: KES },
  ],
  'purchase-payments': [
    { key: 'paymentNumber', header: 'Payment #', width: 16, align: L },
    { key: 'paymentDate', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'supplierName', header: 'Supplier', width: 24, align: L },
    { key: 'amount', header: 'Amount (KES)', width: 16, align: R, format: KES },
    { key: 'paymentMethod', header: 'Method', width: 14, align: L },
    { key: 'status', header: 'Status', width: 12, align: L },
  ],
  production: [
    { key: 'productionNumber', header: 'Batch #', width: 16, align: L },
    { key: 'productionDate', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'purpose', header: 'Purpose', width: 14, align: L },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'status', header: 'Status', width: 14, align: L },
  ],
  deliveries: [
    { key: 'deliveryNumber', header: 'Delivery #', width: 16, align: L },
    { key: 'deliveryDate', header: 'Date', width: 12, align: L, format: DATE },
    { key: 'orderNumber', header: 'Order #', width: 16, align: L },
    { key: 'customerName', header: 'Customer', width: 24, align: L },
    { key: 'driverName', header: 'Driver', width: 20, align: L },
    { key: 'vehicleReg', header: 'Vehicle', width: 14, align: L },
    { key: 'status', header: 'Status', width: 12, align: L },
  ],
  stock: [
    { key: 'productName', header: 'Product', width: 24, align: L },
    { key: 'physicalQuantity', header: 'Physical', width: 12, align: R, format: INT },
    { key: 'reservedQuantity', header: 'Reserved', width: 12, align: R, format: INT },
    { key: 'availableQuantity', header: 'Available', width: 12, align: R, format: INT },
  ],
};
