-- CreateTable
CREATE TABLE `salaries` (
    `id` VARCHAR(191) NOT NULL,
    `salaryNumber` VARCHAR(191) NOT NULL,
    `employeeId` VARCHAR(191) NOT NULL,
    `salaryType` ENUM('WEEKLY', 'MONTHLY') NOT NULL,
    `periodStart` DATETIME(3) NOT NULL,
    `periodEnd` DATETIME(3) NOT NULL,
    `amount` DECIMAL(12, 2) NOT NULL,
    `paymentMethod` ENUM('MPESA', 'CASH', 'BANK_TRANSFER', 'CHEQUE') NOT NULL,
    `paymentReference` VARCHAR(191) NULL,
    `paymentDate` DATETIME(3) NOT NULL,
    `status` ENUM('PENDING', 'APPROVED', 'REVERSED') NOT NULL DEFAULT 'PENDING',
    `notes` TEXT NULL,
    `evidenceStoredFileId` VARCHAR(191) NULL UNIQUE,
    `registeredByUserId` VARCHAR(191) NULL,
    `approvedByUserId` VARCHAR(191) NULL,
    `approvedAt` DATETIME(3) NULL,
    `correctedByUserId` VARCHAR(191) NULL,
    `correctedAt` DATETIME(3) NULL,
    `correctionReason` TEXT NULL,
    `reversedByUserId` VARCHAR(191) NULL,
    `reversedAt` DATETIME(3) NULL,
    `reversalReason` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    UNIQUE INDEX `salaries_salaryNumber_key`(`salaryNumber`),
    UNIQUE INDEX `salaries_evidenceStoredFileId_key`(`evidenceStoredFileId`),
    INDEX `salaries_employeeId_idx`(`employeeId`),
    INDEX `salaries_status_idx`(`status`),
    INDEX `salaries_createdAt_idx`(`createdAt`),
    CONSTRAINT `salaries_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employees`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `salaries_evidenceStoredFileId_fkey` FOREIGN KEY (`evidenceStoredFileId`) REFERENCES `stored_files`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `salaries_registeredByUserId_fkey` FOREIGN KEY (`registeredByUserId`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `salaries_approvedByUserId_fkey` FOREIGN KEY (`approvedByUserId`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `salaries_correctedByUserId_fkey` FOREIGN KEY (`correctedByUserId`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `salaries_reversedByUserId_fkey` FOREIGN KEY (`reversedByUserId`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
